### ISSUE TITLE
1_get_hog_levels.rb did not work after few proteins. 

### ISSUE THREAD

**Issue by zitunstu24** [NAMlab/tomato-rna-meta#1]
# I tried to reproduce this ruby script (`1_get_hog_levels.rb`) to get the HOGs and the deepest level for some of my Lotus proteins. 

## What I changed: 
1. the taxon id in the ruby script. This is the only thing I changed in the script. 

2. the `clades_hierarchy.txt` in the input folder as my own. 

## What I got: 

It printed HOGs and the deepest level in the terminal for first 2-3 proteins and then the following error: 

``` 1_get_hog_levels.rb:19:in `block in <main>': private method `select' called for nil:NilClass (NoMethodError)```

**Comment by Thyra** [comment]
Can you please provide the taxon ID and clades_hierarchy.txt you used so I can reproduce it?

**Comment by zitunstu24** [comment]
[clades_hierarchy.txt](https://github.com/user-attachments/files/17868380/clades_hierarchy.txt)

``` taxon id = 34305```

**Comment by zitunstu24** [comment]
### GitHub Comment Update  

I managed to reproduce the issue.  

The mapping of protein IDs to HOGs did not work directly. I had to perform this step manually using the OMA browser. After mapping, I discovered some HOGs had extensions and incorrect deepest levels.  

Here’s what I did:  
- I modified the Ruby script `1_get_hog_levels.rb` to use only the second loop, where HOG IDs already come with the deepest level. I commented out the first part of the script since it didn’t work as intended.  

Additionally, I encountered a few issues that may be useful for future reference:  

1. **Consistency Between Files**:  
   Ensure you use the same version of the newick tree and orthoXML file of HOGs when performing the pyham analysis (`5_hogprof-mini.py`).  

2. **Pyham Dependency on `ete3`**:  
   The pyham package depends on the `ete3` module, but the latest version is `ete4`, which has differences. You’ll need to manually install `ete3` in your environment. Note that it’s listed in `requirements.txt` for pyham but isn’t automatically installed.  

3. **Pyham Dependency on `cgi`**:  
   Pyham also requires the `cgi` module, which is no longer part of the Python standard library. You can still install it with `pip install legacy-cgi` before running pyham analysis.  

I hope these notes are helpful for others encountering similar issues!

**Comment by Thyra** [comment]
I forgot to ask for your input FASTA but the script did indeed not handle multi-line FASTAs well or cases where an error occurred in the search. That should be fixed now. Could you test it on your input file again and report back if it worked so we can close the issue? If it did not fix the issue, please also provide me the top part of your input FASTA that is triggering the problem.

Re dependencies etc.: this should not be an issue if you install the versions specified in the `Pipfile.lock` file (e.g. by `pipenv install` but it's good that you found your own workaround :-)

**Comment by zitunstu24** [comment]
Thank you @Thyra 🥇 

You can close the issue.
